### PR TITLE
Fix case-sensitivity in discovery

### LINKED ISSUE #133: Auth_OpenID_Parse fails to find link attributes in HTML with uppercase HEAD tag
Offending HTML:
```
<HTML>
<HEAD>
    <TITLE>strk's publications</TITLE>
        <link rel="stylesheet"
     href="style.css" type="text/css">




  <link rel="openid2.provider" href="https://id.xxx.io/" />
  <link rel="openid2.local_id" href="https://strk.xxx.io/openid/" />

</HEAD>
<BODY BGCOLOR="#FFFFFF">
```

The Auth_OpenID_Parse's parseLinkAttrs returns empty when passed that HTML.
Why not using DOM rather than regexps in that function ?

### PR DESCRIPTION
**Pull request by strk**
Fixes #133

### CODE REVIEW

File: Auth/OpenID/Parse.php [hunk 1]
```diff
@@ -218,12 +218,12 @@ function removeQuotes($str)
...
-            if (!preg_match($regexp, $text, $match)) {
-                return false;
-            }
-            $match = $match[0];
-            return true;
+        if (preg_match($regexp, $text, $match)) {
+           return true;
+        }
+
+        if ( !is_callable('mb_ereg_search_init')) {
```
Comment (marcoceppi) [inline Auth/OpenID/Parse.php]: There's no need for this block now.  There was never a need for it since preg_match replaced mb_ereg_search a while ago. Just delete this block and replace it with `return false;`

Comment (marcoceppi) [inline Auth/OpenID/Parse.php]: Also, since you're basically short circuiting the whole method, you can probably just kill lines 229 - 235. If preg_match works as expected.

File: Auth/OpenID/Parse.php [hunk 2]
```diff
@@ -218,12 +218,12 @@ function removeQuotes($str)
     
     function match($regexp, $text, &$match)
     {
-        if (!is_callable('mb_ereg_search_init')) {
-            if (!preg_match($regexp, $text, $match)) {
-                return false;
-            }
-            $match = $match[0];
```
Comment (marcoceppi) [inline Auth/OpenID/Parse.php]: I'm concerned with removing this. [preg_match returns an array](http://php.net/manual/en/function.preg-match.php) the first element is the whole line, the second element is the text capture from `$regexp`. The purpose of this method is to just return the first line.

**Comment by strk** [comment]
I *needed* this change to support my OpenID address
I gladyly simplified the code to drop the mb_ereg_search_init part
so now it's straightforward (see a3d0943).

About match array. I needed that change because otherwise match[0],
used by the caller here:
```
        if (!preg_match_all($this->_link_find, $head_match[0],
                            $link_matches)) {
            ini_set( 'pcre.backtrack_limit', $old_btlimit );
            return array();
        }
```

Was getting a single character.

I guess it wasn't spotted before becuase basically preg_match was never
used, and the mb_ereg_search return code was different...

File: Auth/OpenID/Parse.php (hunk 2 above)
Comment (strk) [inline Auth/OpenID/Parse.php]: Did my comment https://github.com/openid/php-openid/pull/134#issuecomment-287699942 address your concern ? You can check by yourself that it is *expected* that the `match` function returns an array, at least from the function used to extract links (openid rel) from the page.

**Comment by strk** [comment]
@marcoceppi did I not address your concern ? I'm using this change in production with PHP-5.6 in case it helps accepting it (btw: no CI keeping an eye on the code?)

**Comment by strk** [comment]
For the record: this change was also proposed downstream to GNUSocial (after successfully running it in production for some time now): https://git.gnu.io/gnu/gnu-social/merge_requests/140

**Comment by strk** [comment]
@marcoceppi Wordpress plugin is also affected (surely using your library): https://github.com/diso/wordpress-openid/issues/48

**Comment by strk** [comment]
@marcoceppi hello ?

**Comment by strk** [comment]
thanks
